services:
    #ulysse_business_product.brand:
     #   class: Ulysse\Business\ProductBundle\Controller\BrandController

    category_form:
        factory_service: form.factory
        factory_method: createNamed
        class: Symfony\Component\Form\Form
        arguments:
            - category
            - category_form

    category_type:
        class: Ulysse\Business\ProductBundle\Form\Type\CategoryType
        tags:
            - { name: form.type, alias: category_form }

    category_handler:
        class: Ulysse\Business\ProductBundle\Form\Handler\CategoryHandler
        arguments: [@category_form, @request, @doctrine.orm.entity_manager]
        scope: request

    tag_form:
        factory_service: form.factory
        factory_method: createNamed
        class: Symfony\Component\Form\Form
        arguments:
            - tag
            - tag_form

    tag_type:
        class: Ulysse\Business\ProductBundle\Form\Type\TagType
        tags:
            - { name: form.type, alias: tag_form }

    tag_handler:
        class: Ulysse\Business\ProductBundle\Form\Handler\TagHandler
        arguments: [@tag_form, @request, @doctrine.orm.entity_manager]
        scope: request
