services:
    ulysse_user.profile.form.type:
        class: Ulysse\Business\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: ulysse_user_profile }